In [1]:
import pandas as pd
import numpy as np

# Loading data

In [88]:
df = pd.read_csv("databases/iModulon/log_tpm_qc_w_short_low_fpkm.csv")

In [89]:
df.head(5)

,Unnamed: 0,p1k_00001,p1k_00002,p1k_00003,p1k_00004,p1k_00005,p1k_00006,p1k_00007,p1k_00008,p1k_00009,...,p1k_01046,p1k_01047,p1k_01048,p1k_01049,p1k_01050,p1k_01051,p1k_01052,p1k_01053,p1k_01054,p1k_01055
0,b0001,10.473722,10.271944,6.238716,6.608165,9.864757,10.307053,5.566346,6.535876,10.315486,...,9.600793,9.234737,9.607747,9.894369,9.839448,9.892174,9.988233,9.488565,9.221845,10.170968
1,b0002,10.260569,10.368555,11.193605,11.404163,10.497016,10.235690,9.477470,9.811860,10.735874,...,9.446533,8.302502,8.452109,8.363976,8.672402,8.647693,9.675175,8.761815,8.421964,8.483203
2,b0003,9.920277,10.044224,11.045580,11.460140,10.374823,10.216922,9.219235,9.861262,10.528432,...,8.480662,7.449754,7.467061,7.538769,7.723832,7.670143,8.857956,7.922229,7.633727,7.859478
3,b0004,9.936694,10.010638,9.976798,10.330368,9.876910,9.638754,8.258753,8.650959,9.739519,...,9.282031,8.281564,8.364711,8.249902,8.597246,8.722178,9.444481,8.395833,8.590145,8.446588
4,b0005,7.027515,7.237449,6.014337,5.854519,6.950936,6.768425,5.011006,5.137711,6.745798,...,4.206849,2.505517,3.065065,4.168111,4.056920,4.030515,4.921936,3.311463,2.568554,4.185822

In [90]:
df_transposed = df.transpose()

In [91]:
df_transposed.columns = df["Unnamed: 0"]

In [92]:
df_transposed.reset_index(inplace=True)

In [93]:
df_transposed.drop(index=0, inplace=True)

In [94]:
df_transposed.head(2)

Unnamed: 0,index,b0001,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,...,b4748,b4749,b4750,b4751,b4752,b4753,b4754,b4755,b4756,b4757
1,p1k_00001,10.473722,10.260569,9.920277,9.936694,7.027515,6.537183,3.043208,10.664771,5.818691,...,0.0,0.0,3.602317,5.55989,2.256419,2.993813,2.316272,2.164426,4.553727,3.949303
2,p1k_00002,10.271944,10.368555,10.044224,10.010638,7.237449,6.452699,2.933902,10.702458,6.109742,...,0.0,0.0,3.896779,5.638994,3.445133,2.161503,3.989843,2.634758,3.824146,3.73891

In [96]:
df_transposed.columns.name = None

In [97]:
df_transposed

,index,b0001,b0002,b0003,b0004,b0005,b0006,b0007,b0008,b0009,...,b4748,b4749,b4750,b4751,b4752,b4753,b4754,b4755,b4756,b4757
1,p1k_00001,10.473722,10.260569,9.920277,9.936694,7.027515,6.537183,3.043208,10.664771,5.818691,...,0.0,0.0,3.602317,5.55989,2.256419,2.993813,2.316272,2.164426,4.553727,3.949303
2,p1k_00002,10.271944,10.368555,10.044224,10.010638,7.237449,6.452699,2.933902,10.702458,6.109742,...,0.0,0.0,3.896779,5.638994,3.445133,2.161503,3.989843,2.634758,3.824146,3.73891
3,p1k_00003,6.238716,11.193605,11.04558,9.976798,6.014337,6.371349,3.316531,10.641143,6.170178,...,0.0,0.0,4.796333,4.309421,1.063252,1.226105,2.483375,5.02124,2.602983,6.438261
4,p1k_00004,6.608165,11.404163,11.46014,10.330368,5.854519,6.387164,3.264503,10.388623,6.110583,...,0.0,0.0,5.725902,4.301115,1.137593,2.786737,1.819202,5.655869,2.037598,7.101934
5,p1k_00005,9.864757,10.497016,10.374823,9.87691,6.950936,6.321764,3.091241,10.540922,5.82178,...,0.0,0.0,4.874175,5.117821,2.77993,1.208799,2.953192,2.097149,4.222657,3.905814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031,p1k_01051,9.892174,8.647693,7.670143,8.722178,4.030515,6.324962,2.06495,10.900502,5.682865,...,6.65714,0.0,6.006383,5.9229,0.0,0.0,0.0,0.0,0.0,0.0
1032,p1k_01052,9.988233,9.675175,8.857956,9.444481,4.921936,6.092354,3.085454,10.091741,5.505269,...,3.672372,0.0,5.730287,4.33163,0.0,0.0,0.0,0.0,3.142907,0.0
1033,p1k_01053,9.488565,8.761815,7.922229,8.395833,3.311463,5.57895,3.396341,9.674802,5.604988,...,4.138619,0.0,6.33917,5.0647,1.65073,2.646312,0.0,5.813532,3.59404,3.909619
1034,p1k_01054,9.221845,8.421964,7.633727,8.590145,2.568554,5.690213,3.545379,10.018518,5.7651,...,5.809142,0.0,7.249261,5.638891,1.750457,1.965895,0.0,4.314107,3.586631,4.437547
1035,p1k_01055,10.170968,8.483203,7.859478,8.446588,4.185822,5.635963,3.166606,9.951308,5.799087,...,4.465101,0.0,6.281492,5.54807,1.431685,0.0,2.19444,3.96411,5.103798,4.288952

In [98]:
df_transposed.to_csv('datasets/df_iModulon.csv', index=False)